-- Migration 034 : autoriser la réinsertion d'une tâche avec son identifiant
--
-- `planning.id` était `generated ALWAYS as identity` : Postgres refuse alors
-- toute valeur explicite (erreur 428C9), ce qui rend impossible d'annuler une
-- suppression de tâche en restaurant la ligne telle quelle.
--
-- Réinsérer la tâche sous un nouvel identifiant ne convient pas : ses segments
-- (planning_segments.tache_id), ses dépendances (planning_dependances) et les
-- tâches qui la désignent (planning.depends_on) pointeraient dans le vide.
--
-- `BY DEFAULT` conserve exactement le même comportement pour les insertions
-- ordinaires — la séquence continue de fournir l'identifiant quand aucun n'est
-- fourni. Seules les réinsertions de l'historique passent une valeur explicite,
-- toujours inférieure au sommet de la séquence : aucun risque de collision.

alter table planning alter column id set generated by default;

notify pgrst, 'reload schema';
