-- Migration 035 : autoriser la réinsertion d'une phase d'étude avec son identifiant
--
-- Pendant du 034 côté chantier. `planning_etude_phases.id` (créée en 010 sous le
-- nom planning_etude_taches) est `generated ALWAYS as identity` : Postgres refuse
-- toute valeur explicite, ce qui rend impossible d'annuler la suppression d'une
-- phase en restaurant la ligne telle quelle.
--
-- Réinsérer la phase sous un nouvel identifiant ne convient pas : ses segments
-- (planning_etude_segments.phase_id) et les phases qui la désignent
-- (planning_etude_phases.depends_on) pointeraient dans le vide.
--
-- `BY DEFAULT` ne change rien aux insertions ordinaires — la séquence continue
-- de fournir l'identifiant quand aucun n'est fourni. Seules les réinsertions de
-- l'historique passent une valeur explicite, toujours inférieure au sommet de
-- la séquence : aucun risque de collision.

alter table planning_etude_phases alter column id set generated by default;

notify pgrst, 'reload schema';
